#ifndef ALL_H_INCLUDED
#define ALL_H_INCLUDED

#include "ast/base.h"
#include "ast/type.h"
#include "ast/symbol_table.h"
#include "ast/statement.h"
#include "ast/type_builtin.h"
#include "ast/expression.h"
#include "ast/or_expression.h"
#include "ast/and_expression.h"
#include "ast/xor_expression.h"
#include "ast/cast_expression.h"
#include "ast/literal_expression.h"
#include "ast/code_block.h"
#include "ast/if_statement.h"
#include "ast/while_statement.h"
#include "ast/do_statement.h"
#include "ast/type_reference.h"
#include "ast/variable.h"
#include "ast/assign_statement.h"
#include "ast/not_expression.h"
#include "ast/compare_expression.h"
#include "ast/add_expression.h"
#include "ast/fdiv_expression.h"
#include "ast/idiv_expression.h"
#include "ast/mod_expression.h"
#include "ast/mul_expression.h"
#include "ast/neg_expression.h"
#include "ast/sub_expression.h"
#include "ast/unary_plus_expression.h"
#include "ast/builtin_function.h"
#include "ast/initialize_statement.h"
#include "ast/for_statement.h"
#include "ast/type_array.h"
#include "ast/array_index_expression.h"

#endif // ALL_H_INCLUDED
